
# Kowshik P 

## Classification Assignment submitted on 26-Apr-2022
## ------------------------------------------------------------------------
## Model Implemented - Naive-Bayes Classification
## Model 1 - GaussianNB : 0.89
## Model 2 - MultinomialNB : 0.76
## Model 3 - ComplementNB : 0.76
## Model 4 - BernoulliNB : 0.96
## Model 5 - CategoricalNB : Index error
## Performance - Average
## ------------------------------------------------------------------------


In [1]:
import pandas as pd;
import numpy as np;
import matplotlib.pyplot as mat;



In [2]:
clientInformation = pd.read_csv("fraud.csv");

clientInformation

step      type      amount  oldbalanceOrg  newbalanceOrig  \
0         1   PAYMENT     9839.64      170136.00       160296.36   
1         1   PAYMENT     1864.28       21249.00        19384.72   
2         1   PAYMENT    11668.14       41554.00        29885.86   
3         1   PAYMENT     7817.71       53860.00        46042.29   
4         1   PAYMENT     7107.77      183195.00       176087.23   
...     ...       ...         ...            ...             ...   
16421   743  CASH_OUT   339682.13      339682.13            0.00   
16422   743  TRANSFER  6311409.28     6311409.28            0.00   
16423   743  CASH_OUT  6311409.28     6311409.28            0.00   
16424   743  TRANSFER   850002.52      850002.52            0.00   
16425   743  CASH_OUT   850002.52      850002.52            0.00   

       oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0                0.00            0.00        0               0  
1                0.00            0.00        0               0  
2                0.00            0.00        0               0  
3                0.00            0.00        0               0  
4                0.00            0.00        0               0  
...               ...             ...      ...             ...  
16421            0.00       339682.13        1               0  
16422            0.00            0.00        1               0  
16423        68488.84      6379898.11        1               0  
16424            0.00            0.00        1               0  
16425      6510099.11      7360101.63        1               0  

[16426 rows x 9 columns]

In [3]:
clientInformation.shape

(16426, 9)

In [4]:
clientInformation = pd.get_dummies(clientInformation, drop_first = True);

clientInformation

step      amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0         1     9839.64      170136.00       160296.36            0.00   
1         1     1864.28       21249.00        19384.72            0.00   
2         1    11668.14       41554.00        29885.86            0.00   
3         1     7817.71       53860.00        46042.29            0.00   
4         1     7107.77      183195.00       176087.23            0.00   
...     ...         ...            ...             ...             ...   
16421   743   339682.13      339682.13            0.00            0.00   
16422   743  6311409.28     6311409.28            0.00            0.00   
16423   743  6311409.28     6311409.28            0.00        68488.84   
16424   743   850002.52      850002.52            0.00            0.00   
16425   743   850002.52      850002.52            0.00      6510099.11   

       newbalanceDest  isFraud  isFlaggedFraud  type_CASH_OUT  type_DEBIT  \
0                0.00        0               0              0           0   
1                0.00        0               0              0           0   
2                0.00        0               0              0           0   
3                0.00        0               0              0           0   
4                0.00        0               0              0           0   
...               ...      ...             ...            ...         ...   
16421       339682.13        1               0              1           0   
16422            0.00        1               0              0           0   
16423      6379898.11        1               0              1           0   
16424            0.00        1               0              0           0   
16425      7360101.63        1               0              1           0   

       type_PAYMENT  type_TRANSFER  
0                 1              0  
1                 1              0  
2                 1              0  
3                 1              0  
4                 1              0  
...             ...            ...  
16421             0              0  
16422             0              1  
16423             0              0  
16424             0              1  
16425             0              0  

[16426 rows x 12 columns]

In [5]:
clientInformation = clientInformation.drop("isFlaggedFraud", axis = 1);

clientInformation


step      amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0         1     9839.64      170136.00       160296.36            0.00   
1         1     1864.28       21249.00        19384.72            0.00   
2         1    11668.14       41554.00        29885.86            0.00   
3         1     7817.71       53860.00        46042.29            0.00   
4         1     7107.77      183195.00       176087.23            0.00   
...     ...         ...            ...             ...             ...   
16421   743   339682.13      339682.13            0.00            0.00   
16422   743  6311409.28     6311409.28            0.00            0.00   
16423   743  6311409.28     6311409.28            0.00        68488.84   
16424   743   850002.52      850002.52            0.00            0.00   
16425   743   850002.52      850002.52            0.00      6510099.11   

       newbalanceDest  isFraud  type_CASH_OUT  type_DEBIT  type_PAYMENT  \
0                0.00        0              0           0             1   
1                0.00        0              0           0             1   
2                0.00        0              0           0             1   
3                0.00        0              0           0             1   
4                0.00        0              0           0             1   
...               ...      ...            ...         ...           ...   
16421       339682.13        1              1           0             0   
16422            0.00        1              0           0             0   
16423      6379898.11        1              1           0             0   
16424            0.00        1              0           0             0   
16425      7360101.63        1              1           0             0   

       type_TRANSFER  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  
...              ...  
16421              0  
16422              1  
16423              0  
16424              1  
16425              0  

[16426 rows x 11 columns]

In [6]:
independentVariable = clientInformation[["step", "amount", "oldbalanceOrg", "newbalanceOrig", "oldbalanceDest", "newbalanceDest", "type_CASH_OUT", "type_DEBIT", "type_PAYMENT", "type_TRANSFER"]];

independentVariable

step      amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0         1     9839.64      170136.00       160296.36            0.00   
1         1     1864.28       21249.00        19384.72            0.00   
2         1    11668.14       41554.00        29885.86            0.00   
3         1     7817.71       53860.00        46042.29            0.00   
4         1     7107.77      183195.00       176087.23            0.00   
...     ...         ...            ...             ...             ...   
16421   743   339682.13      339682.13            0.00            0.00   
16422   743  6311409.28     6311409.28            0.00            0.00   
16423   743  6311409.28     6311409.28            0.00        68488.84   
16424   743   850002.52      850002.52            0.00            0.00   
16425   743   850002.52      850002.52            0.00      6510099.11   

       newbalanceDest  type_CASH_OUT  type_DEBIT  type_PAYMENT  type_TRANSFER  
0                0.00              0           0             1              0  
1                0.00              0           0             1              0  
2                0.00              0           0             1              0  
3                0.00              0           0             1              0  
4                0.00              0           0             1              0  
...               ...            ...         ...           ...            ...  
16421       339682.13              1           0             0              0  
16422            0.00              0           0             0              1  
16423      6379898.11              1           0             0              0  
16424            0.00              0           0             0              1  
16425      7360101.63              1           0             0              0  

[16426 rows x 10 columns]

In [7]:
dependentVariable = clientInformation[["isFraud"]];

dependentVariable

isFraud
0            0
1            0
2            0
3            0
4            0
...        ...
16421        1
16422        1
16423        1
16424        1
16425        1

[16426 rows x 1 columns]

In [8]:
from sklearn.model_selection import train_test_split;

x_train, x_test, y_train, y_test = train_test_split(independentVariable, dependentVariable, test_size = 1/3, random_state = 0);

In [ ]:
x_train

In [ ]:
y_train

In [ ]:
x_test

In [ ]:
y_test

In [ ]:
#from sklearn.preprocessing import StandardScaler;

#standardization = StandardScaler();

#x_train = standardization.fit_transform(x_train);

#x_test = standardization.transform(x_test);


# GaussianNB
## The best performance is 1

In [9]:
from sklearn.naive_bayes import GaussianNB;

naiveBayesClassifer = GaussianNB();

naiveBayesClassifer.fit(x_train, y_train);


C:\Users\hp\Anaconda3\envs\virtualml\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [10]:
y_pred = naiveBayesClassifer.predict(x_test);

In [11]:
from sklearn.metrics import confusion_matrix;

naiveBayesClassiferConfusionMatrix = confusion_matrix(y_test, y_pred);

print(naiveBayesClassiferConfusionMatrix);


[[2677   45]
 [ 563 2191]]


In [12]:
from sklearn.metrics import classification_report;

naiveBayesClassifierReport = classification_report(y_test, y_pred);

print(naiveBayesClassifierReport);

              precision    recall  f1-score   support

           0       0.83      0.98      0.90      2722
           1       0.98      0.80      0.88      2754

    accuracy                           0.89      5476
   macro avg       0.90      0.89      0.89      5476
weighted avg       0.90      0.89      0.89      5476



# MultinomialNB
## The best performance is 1

In [13]:
from sklearn.naive_bayes import MultinomialNB;

naiveBayesClassifierMultinominal = MultinomialNB();

naiveBayesClassifierMultinominal.fit(x_train, y_train);

C:\Users\hp\Anaconda3\envs\virtualml\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [14]:
y_pred = naiveBayesClassifierMultinominal.predict(x_test);

In [15]:
from sklearn.metrics import confusion_matrix;

naiveBayesMultinominalNBCofusionMatrix = confusion_matrix(y_test, y_pred);

print(naiveBayesMultinominalNBCofusionMatrix);



[[1687 1035]
 [ 291 2463]]


In [16]:
from sklearn.metrics import classification_report;

naiveBayesMultinominalNBClassificationReport = classification_report(y_test, y_pred);

print(naiveBayesMultinominalNBClassificationReport);

              precision    recall  f1-score   support

           0       0.85      0.62      0.72      2722
           1       0.70      0.89      0.79      2754

    accuracy                           0.76      5476
   macro avg       0.78      0.76      0.75      5476
weighted avg       0.78      0.76      0.75      5476



# ComplementNB
## The best performance is 1

In [17]:
from sklearn.naive_bayes import ComplementNB;

naiveBayesClassifierComplementNB = ComplementNB();

naiveBayesClassifierComplementNB.fit(x_train, y_train);

C:\Users\hp\Anaconda3\envs\virtualml\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [18]:
y_pred = naiveBayesClassifierComplementNB.predict(x_test);

In [19]:
from sklearn.metrics import confusion_matrix;

naiveBayesComplementNBconfusionMatrix = confusion_matrix(y_test, y_pred);

print(naiveBayesComplementNBconfusionMatrix);

[[1687 1035]
 [ 291 2463]]


In [20]:
from sklearn.metrics import classification_report;

naiveBayesComplementNBclassificationReport = classification_report(y_test, y_pred);

print(naiveBayesComplementNBclassificationReport);

              precision    recall  f1-score   support

           0       0.85      0.62      0.72      2722
           1       0.70      0.89      0.79      2754

    accuracy                           0.76      5476
   macro avg       0.78      0.76      0.75      5476
weighted avg       0.78      0.76      0.75      5476



# BernoulliNB
## The best performance is 1

In [21]:
from sklearn.naive_bayes import BernoulliNB;

naiveBayesClassifierBernoulliNB = BernoulliNB();

naiveBayesClassifierBernoulliNB.fit(x_train, y_train);

C:\Users\hp\Anaconda3\envs\virtualml\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [22]:
y_pred = naiveBayesClassifierBernoulliNB.predict(x_test);

In [23]:
from sklearn.metrics import confusion_matrix;

naiveBayesBernoulliNBconfusionMatrix = confusion_matrix(y_test, y_pred);

print(naiveBayesBernoulliNBconfusionMatrix);

[[2545  177]
 [  64 2690]]


In [24]:
from sklearn.metrics import classification_report;

naiveBayesBernoulliNBclassificationReport = classification_report(y_test, y_pred);

print(naiveBayesBernoulliNBclassificationReport);


              precision    recall  f1-score   support

           0       0.98      0.93      0.95      2722
           1       0.94      0.98      0.96      2754

    accuracy                           0.96      5476
   macro avg       0.96      0.96      0.96      5476
weighted avg       0.96      0.96      0.96      5476



# CategoricalNB
## The best performance is 1

In [25]:
from sklearn.preprocessing import StandardScaler;

standardization = StandardScaler();

x_train = standardization.fit_transform(x_train);

x_test = standardization.transform(x_test);

In [26]:
from sklearn.naive_bayes import CategoricalNB;

naiveBayesClassifierCategoricalNB = CategoricalNB(fit_prior = True);

naiveBayesClassifierCategoricalNB.fit(x_train, y_train);

C:\Users\hp\Anaconda3\envs\virtualml\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [27]:
y_pred = naiveBayesClassifierCategoricalNB.predict(x_test);

IndexError: index 20 is out of bounds for axis 1 with size 20